version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cat_arcade
      - POSTGRES_PASSWORD=cat_arcade
      - POSTGRES_DB=cat_arcade
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 5432"]
    #network_mode: host
#  backend:
#    container_name: backend
#    build: ./backend/
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      # Vite takes care of most of this for us, but it's good practice for other backends
#      - VITE_DB_HOST=postgres
#      - VITE_IP_ADDR=0.0.0.0
#      - VITE_PORT=8080
#      - VITE_LOGS_DIR=logs/
#    depends_on: #This is a lie
#      - postgres
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "8080:8080"   
    environment:
      - VITE_IP_ADDR=0.0.0.0
      - VITE_PORT=8080
      - VITE_LOGS_DIR=logs/
      - VITE_DB_HOST=127.0.0.1
      - VITE_DB_PORT=5432
      - VITE_DB_USER=cat_arcade
      - VITE_DB_PASS=cat_arcade
      - VITE_DB_NAME=cat_arcade
      - VITE_ADMINISTRATOR_PASSWORD=admin
      - AUTH_SECRET="ae7212782245668a76a77360b33d56995b5de8c0b6109a7d79f59f03863d84dd"
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    container_name: backend
    build: ./frontend
    restart: always
    ports:
      - "5173:5173" 

volumes:
  db:
    driver: local
